project:
  type: website
  output-dir: docs

website:
  title: "Dieters Blog"
  site-url: "https://christofhenkel.github.io/dieters-blog-v2/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/christofhenkel
      - icon: twitter
        href: https://twitter.com/kagglingdieter
      - icon: rss
        href: https://christofhenkel.github.io/dieters-blog-v2/index.xml
format:
  html:
    theme: cosmo
    css: styles.css
